apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: benil5zpz-go 
  janus-idp.io/tekton: benil5zpz-go
  backstage.io/kubernetes-id: benil5zpz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: benil5zpz-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  